name: Test Branch
on:
    push:
        branches-ignore:
            - 'gh-pages'
        tags-ignore:
            - '*'

jobs:
    test-branch:
        name: Test Branch (${{ matrix.os }})
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]

        steps:
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: 8
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 10
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies and compile client
              run: |
                  npm install
                  npm run compile
            - name: Lint
              run: |
                  npm run lint
            - name: Validate User Code
              run: |
                  npm run validate-user-code
            - name: Run Enterprise tests
              env:
                  HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
              run: |
                  npm run coverage
